name: "[github-release-actions] Create Prerelease"
description: "Create a prerelease github version and tag. This action is intended to be run after a PR is merged to main."
inputs:
  release-version:
    description: "Version string for the release"
    required: true
  github-token:
    description: "Token used to authenticate with the GitHub API, typically the value of `secrets.GITHUB_TOKEN`"
    required: true
runs:
  using: "node20"
  main: "../dist/action-create-prerelease.js"
