name: '[github-release-action] Perform Pre-Release'
description: 'Determine if the release is valid. If it is a new release generate a draft. If it is an existing release continue. Intended to run immediately before releasing.'
inputs:
  release-version:
    description: 'The tag name of the target release.'
    required: true
  github-token:
    description: "Token used to authenticate with the GitHub API, typically the value of `secrets.GITHUB_TOKEN`"
    required: true
outputs:
  release-id:
    description: 'The numeric github id of the release to be deployed'
  is-existing-release:
    description: '`true` if this is a rollback/roll forward, `false` if this is a new release'
runs:
  using: 'node20'
  main: '../dist/action-perform-prerelease.js'
