name: '[github-release-action] Perform Post-Release'
description: 'Remove intermediate prereleases. Update the latest release tag to point to the new release. This action is intended to be run immediately after a release.'
inputs:
  release-id:
    description: 'The id of the release that has just been deployed'
    required: true
  github-token:
    description: "Token used to authenticate with the GitHub API, typically the value of `secrets.GITHUB_TOKEN`"
    required: true
runs:
  using: 'node20'
  main: '../dist/action-perform-postrelease.js'
